pub const BATCH_UPLOAD_MAX_BYTES: usize = 10 * 1024 * 1024;
pub const MULTIPART_BODY_OVERHEAD_BYTES: usize = 1024 * 1024;
pub const BATCH_MULTIPART_BODY_LIMIT: usize =
    BATCH_UPLOAD_MAX_BYTES + MULTIPART_BODY_OVERHEAD_BYTES;
